environments:
  default_database: development
  development:
      adapter: mysql
      host: localhost
      name: vandise
      user: root
      pass: ''
      port: 3306
      charset: utf8
      collation: utf8_unicode_ci
  production:
      adapter: mysql
      host: localhost
      name: production_db
      user: user
      pass: ''
      port: 3306
      charset: utf8
      collation: utf8_unicode_ci